#include "pqAutoGeneratedObjectPanel.h"
#include "pqObjectPanelInterface.h"

#include <QObject>
#include <QLabel>
#include <QLayout>
#include <QComboBox>
#include <QLineEdit>


#include "pqPropertyManager.h"
#include "pqNamedWidgets.h"

class pqTrackFilterPanel : public pqAutoGeneratedObjectPanel
{
	Q_OBJECT


public:

	pqTrackFilterPanel(pqProxy* pxy, QWidget* p);
	~pqTrackFilterPanel();

protected slots:
	void ModeChanged(int);

protected:
	QLineEdit * RestrictionBounds_0;
	QLineEdit * RestrictionBounds_1;
	QComboBox * RestrictionArray;
	//QLabel *label1;
	//QLabel *label2;


};