#include "pqTrackFilterPanel.h"

#include <QObject>
#include <QLayout>
#include <QLabel>
#include <QComboBox>

#include "pqSMAdaptor.h"
#include "vtkSMProperty.h"
#include "vtkSMPropertyHelper.h"
#include "pqProxy.h"
#include "vtkSMProxy.h"

pqTrackFilterPanel::pqTrackFilterPanel(pqProxy* pxy, QWidget* p): pqAutoGeneratedObjectPanel(pxy, p)
{
	//this->layout()->addWidget(new QLabel("This is from a plugin", this));

	this->RestrictionArray = this->findChild<QComboBox*>("SelectRestrictionArray");
	this->RestrictionBounds_0 = this->findChild<QLineEdit*>("RestrictionLow");
	this->RestrictionBounds_1 = this->findChild<QLineEdit*>("RestrictionHi");

	this->RestrictionBounds_0->setEnabled(false);
	this->RestrictionBounds_1->setEnabled(false);
	this->RestrictionArray->setEnabled(false);


	QComboBox * comboB = this->findChild<QComboBox*>("Mode");
	QObject::connect(
		comboB,
		SIGNAL(currentIndexChanged(int)),
		this,
		SLOT(ModeChanged(int))
		);

}


pqTrackFilterPanel::~pqTrackFilterPanel()
{
}


void pqTrackFilterPanel::ModeChanged(int selection)
{
	if (selection==2)
	{
		this->RestrictionBounds_0->setEnabled(true);
		this->RestrictionBounds_1->setEnabled(true);
		this->RestrictionArray->setEnabled(true);
	}
	else
	{
		this->RestrictionBounds_0->setEnabled(false);
		this->RestrictionBounds_1->setEnabled(false);
		this->RestrictionArray->setEnabled(false);
	}
}