#include "pqAutoGeneratedObjectPanel.h"
#include "pqObjectPanelInterface.h"

#include <QLabel>
#include <QComboBox>
#include <QLayout>

#include "pqPropertyManager.h"
#include "pqNamedWidgets.h"

class pqTrackFilterPanel:public pqAutoGeneratedObjectPanel
{
	Q_OBJECT
public:
	pqTrackFilterPanel(pqProxy* pxy, QWidget* p) : pqAutoGeneratedObjectPanel(pxy,p)
	{
		QLabel * label1 = new QLabel("Select all Tracks, where the value from Array...");
		QLabel * label2 = new QLabel("... is ...");
		QLabel * label3 = new QLabel("(*some where*/everywhere) on the track between");
		QLabel * label4 = new QLabel(" and ");
		QLabel * label5 = new QLabel(" on the track.");

		QSpacerItem * spacer = new QSpacerItem(0,0);

		QWidget * inpArr = this->findChild<QWidget*>("SelectInputArray");
		QWidget * minVal = this->findChild<QWidget*>("LowPoint");
		QWidget * maxVal = this->findChild<QWidget*>("HighPoint");

		this->PanelLayout->addWidget(label1,0,0);
		this->PanelLayout->addWidget(inpArr,1,0);
		this->PanelLayout->addWidget(label2,2,0);
		this->PanelLayout->addWidget(label3,3,0);
		this->PanelLayout->addWidget(minVal,4,0);
		this->PanelLayout->addWidget(label4,5,0);
		this->PanelLayout->addWidget(maxVal,6,0);
		this->PanelLayout->addWidget(label5,7,0);
		//this->PanelLayout->addWidget(spacer,8,0);
		

	};
	
	~pqTrackFilterPanel() {};

};